from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

from add_amount_region_zone_diagnostics import _image_by_stem, _should_run_for_image

DEFAULT_TARGETS = {
    'AH foto 2',
    'Aldi foto 2',
    'Plus foto 2',
    'plus foto 1',
}
MAX_VERTICAL_DISTANCE_PX = 34
MIN_HORIZONTAL_GAP_PX = -20
MAX_HORIZONTAL_GAP_PX = 600


def _read_key_values(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for line in path.read_text(encoding='utf-8').splitlines():
        if '=' in line:
            key, value = line.split('=', 1)
            values[key.strip()] = value.strip()
    return values


def _candidate_run_paths(raw_run_path: str) -> list[Path]:
    raw = Path(raw_run_path)
    candidates = [raw]
    prefix = Path('tools') / 'receipt_csv_poc'
    prefix_parts = prefix.parts
    parts = raw.parts
    if len(parts) > len(prefix_parts) and parts[:len(prefix_parts)] == prefix_parts:
        candidates.append(Path(*parts[len(prefix_parts):]))
    if raw.name:
        candidates.append(Path('test_runs') / raw.name)
    return candidates


def _is_valid_run_dir(path: Path) -> bool:
    return (path / 'json').exists() and (path / 'benchmark_summary.json').exists()


def _find_latest_valid_run(test_runs_dir: Path = Path('test_runs')) -> Path:
    valid_runs = [path for path in test_runs_dir.glob('run_*') if path.is_dir() and _is_valid_run_dir(path)]
    if not valid_runs:
        raise FileNotFoundError(f'No valid run directory found under {test_runs_dir}')
    return sorted(valid_runs, key=lambda path: path.name)[-1]


def _read_latest_run_path(latest_file: Path) -> Path:
    values = _read_key_values(latest_file)
    raw_run_path = values.get('run_path', '')
    if raw_run_path:
        for candidate in _candidate_run_paths(raw_run_path):
            if _is_valid_run_dir(candidate):
                return candidate
        print(f'[WARN] LATEST_PUSHED_RUN points to invalid or incomplete run: {raw_run_path}')
    fallback = _find_latest_valid_run()
    print(f'[INFO] Using latest valid local run instead: {fallback}')
    return fallback


def _norm(value: str) -> str:
    value = re.sub(r'[^a-z0-9à-ÿ]+', ' ', str(value or '').lower())
    return re.sub(r'\s+', ' ', value).strip()


def _is_non_product_name(text: str) -> bool:
    normalized = _norm(text)
    blocked = (
        'totaal', 'subtotaal', 'betaal', 'pin', 'kaart', 'btw', 'wisselgeld',
        'zegel', 'campagne', 'pluspunt', 'spaarkaart', 'omschrijving', 'prijs',
        'bedrag', 'aantal', 'tel', 'terminal', 'merchant', 'klantticket',
    )
    return any(word in normalized for word in blocked) or len(normalized) < 3


def _box_center_y(box: dict) -> int:
    return int(box.get('center_y', int(box.get('top', 0)) + int(box.get('height', 0)) // 2))


def _box_right(box: dict) -> int:
    return int(box.get('right', int(box.get('left', 0)) + int(box.get('width', 0))))


def _extract_name_regions(receipt_json: dict, zone_diag: dict, variant_name: str) -> list[dict]:
    # Prefer name regions already generated by ocr_region_amount_diagnostics for the original image.
    # For preprocessed variants, use zone_context to keep validation diagnostic-only and conservative.
    ocr_diag = receipt_json.get('metadata', {}).get('ocr_region_amount_diagnostics', {})
    product_regions = []
    for item in ocr_diag.get('orphan_product_name_region_diagnostics', []):
        raw = item.get('product_name_raw_line') or item.get('name_region_text') or ''
        if _is_non_product_name(raw):
            continue
        box = item.get('name_region_box')
        if not box:
            continue
        product_regions.append({
            'product_name_text': item.get('name_region_text') or raw,
            'product_name_raw_line': raw,
            'box': box,
            'source': 'ocr_region_amount_diagnostics',
        })

    # Add explicit orphan names as fallback without boxes; they are useful for reject diagnostics.
    if not product_regions:
        rescue = receipt_json.get('metadata', {}).get('product_block_rescue_diagnostics', {})
        stop_line_no = rescue.get('stop_line_no')
        for orphan in rescue.get('orphan_product_name_lines', []):
            line_no = int(orphan.get('line_no') or 0)
            if stop_line_no is not None and line_no >= int(stop_line_no):
                continue
            raw = orphan.get('raw_line') or ''
            if _is_non_product_name(raw):
                continue
            product_regions.append({
                'product_name_text': raw,
                'product_name_raw_line': raw,
                'box': None,
                'source': 'orphan_product_name_without_region_box',
            })
    return product_regions


def _evaluate_pair(product_region: dict, amount_region: dict) -> tuple[str, str, dict[str, int]]:
    product_box = product_region.get('box')
    amount_box = amount_region.get('box') or {}
    if not product_box:
        return 'rejected', 'product_name_region_box_missing', {}

    vertical_distance = abs(_box_center_y(amount_box) - _box_center_y(product_box))
    horizontal_gap = int(amount_box.get('left', 0)) - _box_right(product_box)
    metrics = {
        'vertical_distance_px': vertical_distance,
        'horizontal_gap_px': horizontal_gap,
    }

    if vertical_distance <= MAX_VERTICAL_DISTANCE_PX and MIN_HORIZONTAL_GAP_PX <= horizontal_gap <= MAX_HORIZONTAL_GAP_PX:
        return 'candidate', 'same_visual_line_left_product_right_amount', metrics
    if vertical_distance > MAX_VERTICAL_DISTANCE_PX:
        return 'rejected', 'vertical_distance_too_large', metrics
    if horizontal_gap < MIN_HORIZONTAL_GAP_PX:
        return 'rejected', 'amount_not_right_of_product_name', metrics
    return 'rejected', 'horizontal_gap_too_large', metrics


def build_article_zone_amount_validation(receipt_json: dict) -> dict[str, object]:
    zone_diag = receipt_json.get('metadata', {}).get('amount_region_zone_diagnostics', {})
    variants_out = []

    for variant in zone_diag.get('variants', []):
        variant_name = str(variant.get('variant') or '')
        article_amounts = [region for region in variant.get('amount_regions', []) if region.get('zone') == 'article_zone']
        name_regions = _extract_name_regions(receipt_json, zone_diag, variant_name)
        validated_pairs = []
        rejected_pairs = []

        for amount_region in article_amounts:
            best_candidate = None
            local_rejects = []
            for product_region in name_regions:
                validation, reason, metrics = _evaluate_pair(product_region, amount_region)
                pair = {
                    'product_name_text': product_region.get('product_name_text'),
                    'product_name_raw_line': product_region.get('product_name_raw_line'),
                    'product_name_box': product_region.get('box'),
                    'amount_text': amount_region.get('text'),
                    'amounts': amount_region.get('amounts', []),
                    'amount_box': amount_region.get('box'),
                    'amount_mean_confidence': amount_region.get('mean_confidence'),
                    'validation': validation,
                    'reason': reason,
                    **metrics,
                    'diagnostic_only': True,
                }
                if validation == 'candidate':
                    if best_candidate is None or pair.get('vertical_distance_px', 999999) < best_candidate.get('vertical_distance_px', 999999):
                        best_candidate = pair
                else:
                    local_rejects.append(pair)
            if best_candidate:
                validated_pairs.append(best_candidate)
            else:
                if local_rejects:
                    rejected_pairs.extend(local_rejects[:5])
                else:
                    rejected_pairs.append({
                        'amount_text': amount_region.get('text'),
                        'amounts': amount_region.get('amounts', []),
                        'amount_box': amount_region.get('box'),
                        'amount_mean_confidence': amount_region.get('mean_confidence'),
                        'validation': 'rejected',
                        'reason': 'no_product_name_region_available_left_of_article_amount',
                        'diagnostic_only': True,
                    })

        variants_out.append({
            'variant': variant_name,
            'article_zone_amount_count': len(article_amounts),
            'validated_pair_count': len(validated_pairs),
            'rejected_pair_count': len(rejected_pairs),
            'validated_pairs': validated_pairs,
            'rejected_pairs': rejected_pairs,
            'diagnostic_only': True,
            'reconstruction_applied': False,
        })

    best_variant = max(
        variants_out,
        key=lambda item: (int(item.get('validated_pair_count', 0)), int(item.get('article_zone_amount_count', 0))),
        default={},
    )
    return {
        'diagnostic_scope': 'article_zone_amount_to_left_product_validation',
        'diagnostic_only': True,
        'reconstruction_applied': False,
        'best_variant': {
            'variant': best_variant.get('variant', ''),
            'article_zone_amount_count': best_variant.get('article_zone_amount_count', 0),
            'validated_pair_count': best_variant.get('validated_pair_count', 0),
            'rejected_pair_count': best_variant.get('rejected_pair_count', 0),
        },
        'limits': {
            'max_vertical_distance_px': MAX_VERTICAL_DISTANCE_PX,
            'min_horizontal_gap_px': MIN_HORIZONTAL_GAP_PX,
            'max_horizontal_gap_px': MAX_HORIZONTAL_GAP_PX,
        },
        'variants': variants_out,
    }


def update_targeted_run(input_dir: Path, output_dir: Path, targets: set[str]) -> None:
    json_dir = output_dir / 'json'
    if not json_dir.exists():
        raise FileNotFoundError(f'JSON output directory not found: {json_dir}')

    image_lookup = _image_by_stem(input_dir)
    summary_path = output_dir / 'benchmark_summary.json'
    summary = json.loads(summary_path.read_text(encoding='utf-8')) if summary_path.exists() else {}
    summary.setdefault('article_zone_amount_validation', {})

    processed = 0
    skipped = 0
    for target in sorted(targets):
        json_path = json_dir / f'{target}.json'
        image_path = image_lookup.get(target)
        if image_path is None or not json_path.exists() or not _should_run_for_image(image_path):
            skipped += 1
            continue
        payload = json.loads(json_path.read_text(encoding='utf-8'))
        diagnostics = build_article_zone_amount_validation(payload)
        payload.setdefault('metadata', {})['article_zone_amount_validation'] = diagnostics
        json_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding='utf-8')
        summary['article_zone_amount_validation'][payload.get('metadata', {}).get('source_file', image_path.name)] = diagnostics
        processed += 1

    summary['schema_version'] = 'receipt-ocr-benchmark-v19-article-zone-amount-validation'
    summary['article_zone_amount_validation_processed_receipts'] = processed
    summary['article_zone_amount_validation_skipped_receipts'] = skipped
    summary['article_zone_amount_validation_targeted_only'] = True
    summary_path.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding='utf-8')
    print(f'[OK] Article zone amount validation added for {processed} receipts; skipped={skipped}')


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument('--input', default='input_receipts')
    parser.add_argument('--output', default='')
    parser.add_argument('--latest-file', default='LATEST_PUSHED_RUN.txt')
    parser.add_argument('--targets', nargs='*', default=sorted(DEFAULT_TARGETS))
    args = parser.parse_args()

    output_dir = Path(args.output) if args.output else _read_latest_run_path(Path(args.latest_file))
    update_targeted_run(Path(args.input), output_dir, set(args.targets))


if __name__ == '__main__':
    main()
