export const PLATFORM_NAVIGATION_GROUPS = Object.freeze([
  { key: 'insight', label: 'Inzicht' },
  { key: 'operations', label: 'Platformbeheer' },
  { key: 'security', label: 'Toegang en veiligheid' },
])

export const PLATFORM_NAVIGATION_ITEMS = Object.freeze([
  {
    key: 'diagnostics',
    group: 'insight',
    permission: 'platform.diagnostics.view',
    label: 'Diagnostiek',
    icon: '🩺',
    route: '/platform/diagnostiek',
    description: 'Bekijk technische diagnostiek van het platform.',
  },
  {
    key: 'logs',
    group: 'insight',
    permission: 'platform.logs.view',
    label: 'Logs',
    icon: '📜',
    route: '/platform/logs',
    description: 'Bekijk platformlogs voor analyse en ondersteuning.',
  },
  {
    key: 'audit',
    group: 'insight',
    permission: 'platform.audit.view',
    label: 'Audit',
    icon: '🔎',
    route: '/platform/audit',
    description: 'Bekijk auditinformatie over platformhandelingen.',
  },
  {
    key: 'integrations',
    group: 'operations',
    permission: 'platform.integrations.manage',
    label: 'Integraties',
    icon: '🔌',
    route: '/platform/integraties',
    description: 'Beheer technische platformintegraties.',
  },
  {
    key: 'background-jobs',
    group: 'operations',
    permission: 'platform.background_jobs.manage',
    label: 'Achtergrondtaken',
    icon: '⚙️',
    route: '/platform/achtergrondtaken',
    description: 'Beheer achtergrondtaken en hun uitvoering.',
  },
  {
    key: 'recovery',
    group: 'operations',
    permission: 'platform.recovery.manage',
    label: 'Herstel',
    icon: '🛟',
    route: '/platform/herstel',
    description: 'Beheer herstelacties voor het platform.',
  },
  {
    key: 'technical-configuration',
    group: 'operations',
    permission: 'platform.technical_configuration.manage',
    label: 'Technische configuratie',
    icon: '🧰',
    route: '/platform/technische-configuratie',
    description: 'Beheer technische platformconfiguratie.',
  },
  {
    key: 'test-fixtures',
    group: 'operations',
    permission: 'platform.test_fixtures.manage',
    label: 'Testfixtures',
    icon: '🧪',
    route: '/platform/testfixtures',
    description: 'Beheer platformbrede testfixtures.',
  },
  {
    key: 'feature-flags',
    group: 'operations',
    permission: 'platform.feature_flags.manage',
    label: 'Featureflags',
    icon: '🚩',
    route: '/platform/featureflags',
    description: 'Beheer platformbrede featureflags.',
  },
  {
    key: 'sessions',
    group: 'security',
    permission: 'platform.sessions.revoke',
    label: 'Sessies',
    icon: '🔐',
    route: '/platform/sessies',
    description: 'Beheer het intrekken van actieve sessies.',
  },
  {
    key: 'users',
    group: 'security',
    permission: 'platform.users.suspend',
    label: 'Gebruikers',
    icon: '👤',
    route: '/platform/gebruikers',
    description: 'Beheer het schorsen van platformgebruikers.',
  },
  {
    key: 'permissions',
    group: 'security',
    permission: 'platform.permissions.manage',
    label: 'Platformautorisaties',
    icon: '🛡️',
    route: '/platform/autorisaties',
    description: 'Beheer platformbrede autorisaties.',
  },
])
