export const APPROVED_UI_COMPONENTS = Object.freeze([
  {
    id: 'app-feedback',
    source: 'src/ui/AppFeedbackProvider.jsx',
    publicApi: 'useAppFeedback().showFeedback',
    purpose: 'Alle tijdelijke applicatiemeldingen en interactieve bevestigingsdialogen.',
    reuseRule: 'Maak geen schermspecifieke tijdelijke feedbackbalk of inline succes/foutmelding wanneer AppFeedback volstaat.',
    contractTests: ['tests/inhuis-feedback-bar.contract.mjs', 'tests/ui-component-reuse.contract.mjs'],
  },
  {
    id: 'button',
    source: 'src/ui/Button.jsx',
    publicApi: 'Button',
    purpose: 'Primaire en secundaire gebruikersacties.',
    reuseRule: 'Gebruik Button in plaats van een lokale gestylede knop, behalve voor een apart goedgekeurd semantisch UI-component.',
    contractTests: ['tests/ui-component-reuse.contract.mjs'],
  },
  {
    id: 'select',
    source: 'src/ui/Select.jsx',
    publicApi: 'Select',
    purpose: 'Gebruikerszichtbare overlay-dropdowns; mobiel met vast zoekveld, maximaal vijf zichtbare opties en interne scroll voor langere lijsten.',
    reuseRule: 'Gebruik Select voor alle gebruikerszichtbare keuzelijsten; op mobiel heeft iedere geopende dropdown hetzelfde zoekbare overlaypatroon, ongeacht de lengte van de optieset. Schermspecifieke of native alternatieven zijn niet toegestaan.',
    contractTests: ['tests/inhuis-select.contract.mjs', 'tests/ui-component-reuse.contract.mjs'],
  },
  {
    id: 'search-candidate-list',
    source: 'src/ui/SearchCandidateList.jsx',
    publicApi: 'SearchCandidateList',
    purpose: 'Direct zichtbare zoekkandidaten volgens de maximum-5-regel.',
    reuseRule: 'Gebruik samen met searchCandidatePolicy; geen lokale kandidaatdropdown maken.',
    contractTests: ['tests/search-candidate-policy.contract.mjs', 'tests/ui-component-reuse.contract.mjs'],
  },
  {
    id: 'catalog-thumbnail',
    source: 'src/ui/CatalogArticleThumbnail.jsx',
    publicApi: 'CatalogArticleThumbnail',
    purpose: 'Representatieve productthumbnail met uniforme fallback.',
    reuseRule: 'Gebruik voor operationele productafbeeldingen; geen losse img/fallbackcombinatie maken.',
    contractTests: ['tests/catalog-product-image.contract.mjs', 'tests/ui-component-reuse.contract.mjs'],
  },
  {
    id: 'delayed-table-loading-overlay',
    source: 'src/ui/DelayedTableLoadingOverlay.jsx',
    publicApi: 'DelayedTableLoadingOverlay',
    purpose: 'Tabel-/actie-loadingoverlay na 1000 ms met het Inhuis-beeldmerk.',
    reuseRule: 'Geen lokale spinner, letter-R of alternatieve tabeloverlay toevoegen.',
    contractTests: ['tests/ui-component-reuse.contract.mjs'],
  },
  {
    id: 'table',
    source: 'src/ui/Table.jsx',
    publicApi: 'Table',
    purpose: 'Canonieke tabelbasis, sticky kop en uitlijning.',
    reuseRule: 'Nieuwe tabulaire schermen gebruiken Table/DataTable en bestaande resize-/filterpatronen.',
    contractTests: ['tests/fixed-table-width.contract.mjs', 'tests/ui-component-reuse.contract.mjs'],
  },
  {
    id: 'data-table',
    source: 'src/ui/DataTable.jsx',
    publicApi: 'DataTable',
    purpose: 'Datagedreven tabel met canonieke tabelinteractie.',
    reuseRule: 'Gebruik DataTable waar bestaande tabelinteractie nodig is; geen parallel tabelraamwerk maken.',
    contractTests: ['tests/ui-component-reuse.contract.mjs'],
  },
  {
    id: 'mobile-module-header',
    source: 'src/ui/MobileModuleHeader.jsx',
    publicApi: 'MobileModuleHeader',
    purpose: 'Goedgekeurde compacte mobiele moduleheader met gedeelde Terug-knop, titel en wit Inhuis-logo.',
    reuseRule: 'Gemigreerde mobiele modulehoofschermen gebruiken deze header in plaats van lokale header- of terugknop-markup.',
    contractTests: ['tests/mobile-ui-conformity.contract.mjs', 'tests/ui-component-reuse.contract.mjs'],
  },
  {
    id: 'mobile-recent-actions',
    source: 'src/ui/MobileRecentActionsBar.jsx',
    publicApi: 'MobileRecentActionsBar',
    purpose: 'Vaste mobiele balk voor recente beschikbare acties plus Meer.',
    reuseRule: 'De centrale MobileAppChrome rendert deze balk voor iedere beveiligde mobiele route; schermen implementeren geen eigen bottom navigation.',
    contractTests: ['tests/mobile-ui-conformity.contract.mjs', 'tests/ui-component-reuse.contract.mjs'],
  },
  {
    id: 'quantity-stepper',
    source: 'src/ui/QuantityStepper.jsx',
    publicApi: 'QuantityStepper ({ valueEditable, valueDisabled, onValueCommit })',
    purpose: 'Goedgekeurde − waarde + bediening met optionele directe numerieke aantalinvoer.',
    reuseRule: 'Gebruik voor dezelfde min/plus- en directe aantalinteractie; het component levert touch/keyboardgedrag, terwijl domeinmutatie en de beslissing of een waarde veilig inline bewerkbaar is in de caller blijven.',
    contractTests: ['tests/mobile-voorraad.contract.mjs', 'tests/ui-component-reuse.contract.mjs'],
  },
])

export const EXISTING_UI_MODULES_REQUIRING_FUTURE_REVIEW = Object.freeze([
  'src/ui/AuthorizedControl.jsx',
  'src/ui/BrandLogo.jsx',
  'src/ui/Card.jsx',
  'src/ui/Checkbox.jsx',
  'src/ui/Header.jsx',
  'src/ui/Input.jsx',
  'src/ui/MetricTrendCard.jsx',
  'src/ui/Pagination.jsx',
  'src/ui/ScreenCard.jsx',
  'src/ui/Tabs.jsx',
  'src/ui/resizableTable.jsx',
])

export const SCREEN_COMPONENT_REQUIREMENTS = Object.freeze([
  {
    id: 'mobile-app-chrome',
    source: 'src/app/MobileAppChrome.jsx',
    requiredTokens: [
      'MobileRecentActionsBar',
      'mobile-global-bottom-nav',
    ],
  },
  {
    id: 'mobile-voorraad',
    source: 'src/pages/MobileVoorraad.jsx',
    requiredTokens: [
      'useAppFeedback',
      'Button',
      'Select',
      'CatalogArticleThumbnail',
      'MobileModuleHeader',
      'QuantityStepper',
    ],
  },
  {
    id: 'mobile-voorraad-detail',
    source: 'src/features/articles/MobileArticlePage.jsx',
    requiredTokens: [
      'useAppFeedback',
      'CatalogArticleThumbnail',
      'MobileModuleHeader',
      'Select',
      'QuantityStepper',
    ],
  },
])
