export const APPROVED_UI_COMPONENTS = Object.freeze([
  {
    id: 'app-feedback',
    source: 'src/ui/AppFeedbackProvider.jsx',
    publicApi: 'useAppFeedback().showFeedback',
    purpose: 'Alle tijdelijke applicatiemeldingen en interactieve bevestigingsdialogen.',
    reuseRule: 'Maak geen schermspecifieke tijdelijke feedbackbalk of inline succes/foutmelding wanneer AppFeedback volstaat.',
    contractTests: ['tests/inhuis-feedback-bar.contract.mjs', 'tests/ui-component-reuse.contract.mjs'],
  },
  {
    id: 'button',
    source: 'src/ui/Button.jsx',
    publicApi: 'Button',
    purpose: 'Primaire en secundaire gebruikersacties.',
    reuseRule: 'Gebruik Button in plaats van een lokale gestylede knop, behalve voor een apart goedgekeurd semantisch UI-component.',
    contractTests: ['tests/ui-component-reuse.contract.mjs'],
  },
  {
    id: 'select',
    source: 'src/ui/Select.jsx',
    publicApi: 'Select',
    purpose: 'Gebruikerszichtbare dropdowns met Inhuis-typografie en interactie.',
    reuseRule: 'Gebruik Select voor gebruikerszichtbare keuzelijsten; voeg geen schermspecifieke dropdownimplementatie toe.',
    contractTests: ['tests/inhuis-select.contract.mjs', 'tests/ui-component-reuse.contract.mjs'],
  },
  {
    id: 'search-candidate-list',
    source: 'src/ui/SearchCandidateList.jsx',
    publicApi: 'SearchCandidateList',
    purpose: 'Direct zichtbare zoekkandidaten volgens de maximum-5-regel.',
    reuseRule: 'Gebruik samen met searchCandidatePolicy; geen lokale kandidaatdropdown maken.',
    contractTests: ['tests/search-candidate-policy.contract.mjs', 'tests/ui-component-reuse.contract.mjs'],
  },
  {
    id: 'catalog-thumbnail',
    source: 'src/ui/CatalogArticleThumbnail.jsx',
    publicApi: 'CatalogArticleThumbnail',
    purpose: 'Representatieve productthumbnail met uniforme zichtbare fallback “Geen foto”.',
    reuseRule: 'Gebruik op ieder gebruikersscherm met artikelen voor productafbeeldingen; maak geen losse img/fallbackcombinatie en toon bij ontbrekende/mislukte afbeelding altijd “Geen foto”.',
    contractTests: ['tests/catalog-product-image.contract.mjs', 'tests/ui-component-reuse.contract.mjs'],
  },
  {
    id: 'delayed-table-loading-overlay',
    source: 'src/ui/DelayedTableLoadingOverlay.jsx',
    publicApi: 'DelayedTableLoadingOverlay',
    purpose: 'Tabel-/actie-loadingoverlay na 1000 ms met het Inhuis-beeldmerk.',
    reuseRule: 'Geen lokale spinner, letter-R of alternatieve tabeloverlay toevoegen.',
    contractTests: ['tests/ui-component-reuse.contract.mjs'],
  },
  {
    id: 'table',
    source: 'src/ui/Table.jsx',
    publicApi: 'Table',
    purpose: 'Canonieke tabelbasis, sticky kop en uitlijning.',
    reuseRule: 'Nieuwe tabulaire schermen gebruiken Table/DataTable en bestaande resize-/filterpatronen.',
    contractTests: ['tests/fixed-table-width.contract.mjs', 'tests/ui-component-reuse.contract.mjs'],
  },
  {
    id: 'data-table',
    source: 'src/ui/DataTable.jsx',
    publicApi: 'DataTable',
    purpose: 'Datagedreven tabel met canonieke tabelinteractie.',
    reuseRule: 'Gebruik DataTable waar bestaande tabelinteractie nodig is; geen parallel tabelraamwerk maken.',
    contractTests: ['tests/ui-component-reuse.contract.mjs'],
  },
  {
    id: 'mobile-module-header',
    source: 'src/ui/MobileModuleHeader.jsx',
    publicApi: 'MobileModuleHeader',
    purpose: 'Goedgekeurde compacte mobiele moduleheader met titel links en wit Inhuis-logo rechts.',
    reuseRule: 'Gemigreerde mobiele modulehoofschermen gebruiken deze header in plaats van lokale header-markup.',
    contractTests: ['tests/mobile-ui-conformity.contract.mjs', 'tests/ui-component-reuse.contract.mjs'],
  },
  {
    id: 'mobile-recent-actions',
    source: 'src/ui/MobileRecentActionsBar.jsx',
    publicApi: 'MobileRecentActionsBar',
    purpose: 'Vaste mobiele balk voor recente beschikbare acties plus Meer.',
    reuseRule: 'Gemigreerde mobiele modulehoofschermen gebruiken deze renderer; selectie/exclusie van de actieve module blijft callerlogica.',
    contractTests: ['tests/mobile-ui-conformity.contract.mjs', 'tests/ui-component-reuse.contract.mjs'],
  },
  {
    id: 'mobile-back-button',
    source: 'src/ui/MobileBackButton.jsx',
    publicApi: 'MobileBackButton ({ fallbackRoute })',
    purpose: 'Canonieke mobiele Terug-knop met history-first navigatie en veilige fallback.',
    reuseRule: 'Mobiele schermen maken geen eigen Terug-knop of hard gecodeerde terugactie.',
    contractTests: ['tests/mobile-ui-conformity.contract.mjs', 'tests/ui-component-reuse.contract.mjs'],
  },
  {
    id: 'mobile-app-bottom-navigation',
    source: 'src/ui/MobileAppBottomNavigation.jsx',
    publicApi: 'MobileAppBottomNavigation ({ activeKey })',
    purpose: 'Canonieke onderste mobiele navigatie op ieder gemigreerd mobiel scherm.',
    reuseRule: 'Bottom navigation wordt niet per scherm samengesteld; gebruik deze gedeelde authority.',
    contractTests: ['tests/mobile-ui-conformity.contract.mjs', 'tests/ui-component-reuse.contract.mjs'],
  },
  {
    id: 'mobile-screen-shell',
    source: 'src/ui/MobileScreenShell.jsx',
    publicApi: 'MobileScreenShell ({ title, activeKey, testId, className, rootProps, children })',
    purpose: 'Canonieke mobiele schermshell met header, Terug en bottom navigation.',
    reuseRule: 'Ieder nieuw of gemigreerd mobiel applicatiescherm gebruikt deze shell zodat navigatie, kleur en spacing niet per scherm kunnen afwijken.',
    contractTests: ['tests/mobile-ui-conformity.contract.mjs', 'tests/ui-component-reuse.contract.mjs'],
  },
  {
    id: 'quantity-stepper',
    source: 'src/ui/QuantityStepper.jsx',
    publicApi: 'QuantityStepper ({ valueEditable, valueDisabled, onValueCommit })',
    purpose: 'Goedgekeurde − waarde + bediening met optionele directe numerieke aantalinvoer.',
    reuseRule: 'Gebruik voor dezelfde min/plus- en directe aantalinteractie; het component levert touch/keyboardgedrag, terwijl domeinmutatie en de beslissing of een waarde veilig inline bewerkbaar is in de caller blijven.',
    contractTests: ['tests/mobile-voorraad.contract.mjs', 'tests/ui-component-reuse.contract.mjs'],
  },
])

export const EXISTING_UI_MODULES_REQUIRING_FUTURE_REVIEW = Object.freeze([
  'src/ui/AuthorizedControl.jsx',
  'src/ui/BrandLogo.jsx',
  'src/ui/Card.jsx',
  'src/ui/Checkbox.jsx',
  'src/ui/Header.jsx',
  'src/ui/Input.jsx',
  'src/ui/MetricTrendCard.jsx',
  'src/ui/Pagination.jsx',
  'src/ui/ScreenCard.jsx',
  'src/ui/Tabs.jsx',
  'src/ui/resizableTable.jsx',
])

export const SCREEN_COMPONENT_REQUIREMENTS = Object.freeze([
  {
    id: 'mobile-voorraad',
    source: 'src/pages/MobileVoorraad.jsx',
    requiredTokens: [
      'useAppFeedback',
      'Button',
      'Select',
      'CatalogArticleThumbnail',
      'MobileModuleHeader',
      'MobileRecentActionsBar',
      'QuantityStepper',
    ],
  },
  {
    id: 'mobile-voorraad-detail',
    source: 'src/features/articles/MobileArticlePage.jsx',
    requiredTokens: [
      'useAppFeedback',
      'CatalogArticleThumbnail',
      'MobileModuleHeader',
      'Select',
      'QuantityStepper',
    ],
  },
])
