from __future__ import annotations

import argparse
import csv
from dataclasses import dataclass
from pathlib import Path
import re
import sys

EXPECTED_COUNT = 14
REQUIRED_COLUMNS = {
    'fixture_file',
    'store',
    'baseline_receipt_id',
    'expected_total',
    'expected_line_count',
    'target_status',
    'in_scope',
    'match_status',
}

STORE_BY_RECEIPT_ID = {
    'R002': 'ah',
    'R003': 'ah',
    'R011': 'ah',
    'R027': 'ah',
    'R012': 'aldi',
    'R013': 'aldi',
    'R016': 'jumbo',
    'R015': 'jumbo',
    'R017': 'jumbo',
    'R018': 'lidl',
    'R019': 'lidl',
    'R007': 'lidl',
    'R028': 'plus',
    'R014': 'plus',
}

SOURCE_ORDER = {
    'app': 1,
    'foto': 2,
    'photo': 2,
    'scan': 3,
}

@dataclass(frozen=True)
class CanonicalFixture:
    canonical_fixture_id: str
    baseline_receipt_id: str
    store_slug: str
    source_kind: str
    fixture_file: str
    expected_total: str
    expected_line_count: str
    target_status: str


def normalize_text(value: str) -> str:
    return re.sub(r'\s+', ' ', str(value or '').strip())


def slugify(value: str) -> str:
    value = normalize_text(value).lower()
    value = re.sub(r'[^a-z0-9]+', '_', value)
    return value.strip('_')


def source_kind_from_filename(filename: str) -> str:
    key = filename.lower()
    for source_kind in SOURCE_ORDER:
        if source_kind in key:
            return 'foto' if source_kind == 'photo' else source_kind
    return 'unknown'


def canonical_id(row: dict[str, str]) -> str:
    receipt_id = normalize_text(row.get('baseline_receipt_id', '')).upper()
    store_slug = STORE_BY_RECEIPT_ID.get(receipt_id) or slugify(row.get('store', 'unknown'))
    source_kind = source_kind_from_filename(row.get('fixture_file', ''))
    file_stem = Path(row.get('fixture_file', '')).stem
    source_slug = slugify(file_stem)
    return f'sm_{receipt_id.lower()}_{store_slug}_{source_kind}_{source_slug}'


def read_registry(path: Path) -> list[dict[str, str]]:
    with path.open('r', encoding='utf-8-sig', newline='') as handle:
        reader = csv.DictReader(handle)
        columns = set(reader.fieldnames or [])
        missing = REQUIRED_COLUMNS - columns
        if missing:
            raise SystemExit(f'Missing required CSV columns: {sorted(missing)}')
        return [dict(row) for row in reader]


def build_canonical(row: dict[str, str]) -> CanonicalFixture:
    receipt_id = normalize_text(row['baseline_receipt_id']).upper()
    store_slug = STORE_BY_RECEIPT_ID.get(receipt_id) or slugify(row['store'])
    return CanonicalFixture(
        canonical_fixture_id=canonical_id(row),
        baseline_receipt_id=receipt_id,
        store_slug=store_slug,
        source_kind=source_kind_from_filename(row['fixture_file']),
        fixture_file=normalize_text(row['fixture_file']),
        expected_total=normalize_text(row['expected_total']),
        expected_line_count=normalize_text(row['expected_line_count']),
        target_status=normalize_text(row['target_status']),
    )


def sort_key(item: CanonicalFixture) -> tuple[str, int, str, str]:
    receipt_num_match = re.search(r'\d+', item.baseline_receipt_id)
    receipt_num = int(receipt_num_match.group(0)) if receipt_num_match else 999999
    return item.store_slug, receipt_num, item.source_kind, item.fixture_file.lower()


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description='R7c-3 canonical supermarket fixture registry validator')
    parser.add_argument('--registry', required=True, help='CSV generated by check_r7c2_supermarket_fixture_registry.py')
    parser.add_argument('--csv-out', default='', help='Optional CSV output path for canonical registry')
    args = parser.parse_args(argv)

    registry_path = Path(args.registry)
    if not registry_path.exists():
        raise SystemExit(f'Missing registry CSV: {registry_path}')

    rows = read_registry(registry_path)
    fixtures = [build_canonical(row) for row in rows]
    failures: list[str] = []

    if len(fixtures) != EXPECTED_COUNT:
        failures.append(f'Expected {EXPECTED_COUNT} supermarket fixtures, found {len(fixtures)}')

    non_matched = [row.get('fixture_file', '') for row in rows if normalize_text(row.get('match_status', '')) != 'matched']
    if non_matched:
        failures.append(f'All fixtures must be matched; non-matched: {non_matched}')

    non_supermarket = [row.get('fixture_file', '') for row in rows if normalize_text(row.get('in_scope', '')) != 'supermarket']
    if non_supermarket:
        failures.append(f'All fixtures must be in supermarket scope; invalid: {non_supermarket}')

    wrong_target = [row.get('fixture_file', '') for row in rows if normalize_text(row.get('target_status', '')) != 'Gecontroleerd']
    if wrong_target:
        failures.append(f'All fixtures must target Gecontroleerd; invalid: {wrong_target}')

    ids = [fixture.canonical_fixture_id for fixture in fixtures]
    duplicates = sorted({item for item in ids if ids.count(item) > 1})
    if duplicates:
        failures.append(f'Duplicate canonical fixture ids: {duplicates}')

    missing_store_mapping = sorted(
        fixture.baseline_receipt_id for fixture in fixtures if fixture.baseline_receipt_id not in STORE_BY_RECEIPT_ID
    )
    if missing_store_mapping:
        failures.append(f'Missing fixed store mapping for receipt ids: {missing_store_mapping}')

    print('R7c-3 canonical supermarket fixture registry')
    print(f'- Canonical fixtures: {len(fixtures)}')
    print(f'- Unique canonical ids: {len(set(ids))}')
    print(f'- Store distribution:')
    for store_slug in sorted({fixture.store_slug for fixture in fixtures}):
        print(f'  - {store_slug}: {sum(1 for fixture in fixtures if fixture.store_slug == store_slug)}')

    print('\nCanonical registry:')
    for fixture in sorted(fixtures, key=sort_key):
        print(
            f'- {fixture.canonical_fixture_id}: {fixture.fixture_file} '
            f'({fixture.baseline_receipt_id}, total={fixture.expected_total}, lines={fixture.expected_line_count})'
        )

    if args.csv_out:
        out = Path(args.csv_out)
        out.parent.mkdir(parents=True, exist_ok=True)
        with out.open('w', encoding='utf-8', newline='') as handle:
            fieldnames = [
                'canonical_fixture_id',
                'baseline_receipt_id',
                'store_slug',
                'source_kind',
                'fixture_file',
                'expected_total',
                'expected_line_count',
                'target_status',
            ]
            writer = csv.DictWriter(handle, fieldnames=fieldnames)
            writer.writeheader()
            for fixture in sorted(fixtures, key=sort_key):
                writer.writerow(fixture.__dict__)
        print(f'\nCanonical CSV written: {out}')

    if failures:
        print('\nR7c-3 canonical registry check failed:')
        for failure in failures:
            print('-', failure)
        return 1

    print('\nR7c-3 canonical registry check passed.')
    return 0


if __name__ == '__main__':
    raise SystemExit(main(sys.argv[1:]))
